// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcRfWoHx2PaGlCXNvEbAla-audr_c22Hc',
    appId: '1:267709821744:web:6bc289a38733bd317f8ef5',
    messagingSenderId: '267709821744',
    projectId: 'knowai-cf1d4',
    authDomain: 'knowai-cf1d4.firebaseapp.com',
    storageBucket: 'knowai-cf1d4.appspot.com',
    measurementId: 'G-LT55BEMR0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwcPnRe8amX695LKiGotvK9ddYZAEjwc',
    appId: '1:267709821744:android:e4f3a52ef3fc5a6b7f8ef5',
    messagingSenderId: '267709821744',
    projectId: 'knowai-cf1d4',
    storageBucket: 'knowai-cf1d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNu-GH618IR3zExZ6_A1NU5Gm6TJB_dc',
    appId: '1:267709821744:ios:dfbe0a327c1f7b5f7f8ef5',
    messagingSenderId: '267709821744',
    projectId: 'knowai-cf1d4',
    storageBucket: 'knowai-cf1d4.appspot.com',
    iosBundleId: 'com.giammy.knowai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNu-GH618IR3zExZ6_A1NU5Gm6TJB_dc',
    appId: '1:267709821744:ios:dfbe0a327c1f7b5f7f8ef5',
    messagingSenderId: '267709821744',
    projectId: 'knowai-cf1d4',
    storageBucket: 'knowai-cf1d4.appspot.com',
    iosBundleId: 'com.giammy.knowai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcRfWoHx2PaGlCXNvEbAla-audr_c22Hc',
    appId: '1:267709821744:web:6bc289a38733bd317f8ef5',
    messagingSenderId: '267709821744',
    projectId: 'knowai-cf1d4',
    authDomain: 'knowai-cf1d4.firebaseapp.com',
    storageBucket: 'knowai-cf1d4.appspot.com',
    measurementId: 'G-LT55BEMR0S',
  );

}